import {
  IconBook,
  IconBuildingWarehouse,
  IconCar,
  IconCurrencyRupee,
  IconFileInvoice,
  IconFileText,
  IconListDetails,
  IconMap,
  IconMapPin,
  IconNotebook,
  IconPackages,
  IconReceipt,
  IconReport,
  IconRoute,
  IconTags,
  IconTruck,
  IconTruckDelivery,
  IconUserCheck,
} from '@tabler/icons-react'

export const reportLinks = [
    {
        title: 'Day Book & Registers',
        icon: IconBook,
        description: 'View daily transaction summaries, receipts, and distributor activity',
        visible: true,
        menus: [
            {
                title: 'Day Book',
                icon: IconNotebook,
                href: '/reports/day_book',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Receipt Book',
                icon: IconReceipt,
                href: '/reports/receipt_book',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Distributor Book',
                icon: IconTruckDelivery,
                href: '/reports/distributor_book',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Day Book (Self)',
                icon: IconUserCheck,
                href: '/reports/day_book/self',
                visible: true,
                isActive: false,
                disabled: false,
            },
        ]
    },
    {
        title: 'Stock & Inventory',
        icon: IconPackages,
        description: 'Analyze stock-in-hand across items, godowns, zones, vouchers, and batches',
        visible: true,
        menus: [
            {
                title: 'Stock In Hand (Item Summary)',
                icon: IconReport,
                href: '/reports/stock_summary/stock-in-hand',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Stock In Hand (Godown Wise)',
                icon: IconBuildingWarehouse,
                href: '/reports/stock_summary/stock-in-hand-godown-wise',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Stock In Hand (Zone Wise)',
                icon: IconMap,
                href: '/reports/stock_summary/stock-in-hand-zone-wise',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Stock In Hand (Item Wise)',
                icon: IconListDetails,
                href: '/reports/stock_summary/stock-in-hand-item-wise',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Stock In Hand (Voucher Wise)',
                icon: IconFileInvoice,
                href: '/reports/stock_summary/stock-in-hand-voucher-wise',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Stock In Hand (Batch Wise)',
                icon: IconTags,
                href: '/reports/stock_summary/stock-in-hand-batch-wise',
                visible: false,
                isActive: false,
                disabled: false,
            },
        ]
    },
    {
        title: 'Freight & Logistics',
        icon: IconTruck,
        description: 'Track freight costs, delivery notes, and transporter/vehicle performance',
        visible: true,
        menus: [
            {
                title: 'Delivery Note (Zone Wise)',
                icon: IconMapPin,
                href: '/reports/freight/delivery-note-zone-wise',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Delivery Note (Godown Wise)',
                icon: IconBuildingWarehouse,
                href: '/reports/freight/delivery-note-godown-wise',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Freight (Zone Wise)',
                icon: IconRoute,
                href: '/reports/freight/freight-zone-wise',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Freight (Transporter Wise)',
                icon: IconTruck,
                href: '/reports/freight/freight-transporter-wise',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Freight (Voucher Wise)',
                icon: IconFileText,
                href: '/reports/freight/freight-voucher-wise',
                visible: true,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Freight (Godown Wise)',
                icon: IconBuildingWarehouse,
                href: '/reports/freight/freight-godown-wise',
                visible: false,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Freight (Vehicle Wise)',
                icon: IconCar,
                href: '/reports/freight/freight-vehicle-wise',
                visible: false,
                isActive: false,
                disabled: false,
            },
            {
                title: 'Freight (Billing Preference)',
                icon: IconCurrencyRupee,
                href: '/reports/freight/freight-billing-preference',
                visible: false,
                isActive: false,
                disabled: false,
            },
        ]
    }
]